version: "3.9"
services:
  prestashop_rbm_db:
    image: mysql:5.7
    container_name: ps-database.local
    ports:
      - 3307:3306
    volumes: 
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=rbm-prestashop

  prestashop_rbm_shop:
    container_name: ps-rbm.local
    image: prestashop-rbm
    build:
      context: ""
      dockerfile: Dockerfile
    ports:
      - ${PORT:-8080}:80
    volumes:
      - ./modules/foobar:/var/www/html/modules/foobar
    environment:
      - DB_SERVER=ps-database.local
      - DB_USER=root
      - DB_PASSWD=admin
      - DB_NAME=rbm-prestashop
      - PS_HANDLE_DYNAMIC_DOMAIN=0
      - PS_INSTALL_AUTO=1
      - PS_DEV_MODE=1
      - PS_LANGUAGE=${PS_LANGUAGE:-en}
      - PS_COUNTRY=${PS_COUNTRY:-US}
      - PS_ALL_LANGUAGES=${PS_ALL_LANGUAGES:-0}
      - PS_FOLDER_ADMIN=admin-dev
      - PS_FOLDER_INSTALL=install-dev
      - XDEBUG=yes
      - PS_DOMAIN=${RBM_NAME}.${TUNNEL_DOMAIN:-tunnel.prestashop.net}
      - ADMIN_MAIL=${ADMIN_MAIL:-admin@prestashop.com}
      - ADMIN_PASSWD=${ADMIN_PASSWD:-prestashop}
    depends_on:
      - prestashop_tunnel
      - prestashop_rbm_db

  prestashop_tunnel:
    container_name: ps-tunnel.local
    restart: always
    image: prestashop-tunnel
    build:
      context: "tunnel"
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT:-8080}
      - TUNNEL_DOMAIN=${TUNNEL_DOMAIN:-tunnel.prestashop.net}
    network_mode: host

networks:
  default:
    external: true
    name: prestashop_net