version: '3'
services:
  prestashop_rbm_shop:
    image: prestashop/prestashop
    container_name: ps-rbm.local
    networks:
      - prestashop_net
    ports:
      - 8080:80
    volumes:
      - ./modules/rbm_example:/var/www/html/modules/rbm_example
    environment:
      - DB_SERVER=ps-database.local
      - DB_USER=root
      - DB_PASSWD=admin
      - DB_NAME=rbm-prestashop
      - PS_HANDLE_DYNAMIC_DOMAIN=0
      - PS_INSTALL_AUTO=1
      - PS_DEV_MODE=0
      - PS_LANGUAGE=fr
      - PS_COUNTRY=FR
      - PS_FOLDER_ADMIN=admin-dev
      - PS_FOLDER_INSTALL=install-dev
      - XDEBUG=yes
      - PS_DOMAIN=localhost:8080
      - ADMIN_MAIL=demo@prestashop.com
      - ADMIN_PASSWD=prestashop_demo
    depends_on:
      - prestashop_rbm_db

  prestashop_rbm_db:
    image: mariadb:10
    container_name: ps-database.local
    networks:
      - prestashop_net
    ports:
      - 3307:3306
    volumes: 
      - ./mysql:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_DATABASE=rbm-prestashop
    command: mysqld --default-authentication-plugin=mysql_native_password

  prestashop_tunnel:
    image: efrecon/localtunnel
    networks:
      - prestashop_net
    depends_on:
      - prestashop_rbm_shop
    command: --local-host prestashop_rbm_shop --port 8080 --subdomain prestashop-rbm-dev


networks:
  prestashop_net:
