[build]
  base = "docs"
  publish = "/.vuepress/dist"
  command = "vuepress build ."

[[redirects]]
  from = "https://billing-docs.netlify.app"
  to = "https://docs.cloud.prestashop.com"
  status = 301
  force = true

[[redirects]]
  from = "https://billing-docs.netlify.app"
  to = "https://docs.cloud.prestashop.com"
  status = 301
  force = true