services:
  rbm_example.module:
    class: Rbm_example
    public: true
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'rbm_example'

  rbm_example.context:
    class: Context
    public: true
    factory: ['Context', 'getContext']

  #####################
  # PS Account

  ps_accounts.installer:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Installer'
    public: true
    arguments:
      - '5.0'

  ps_accounts.facade:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
    public: true
    arguments:
      - '@ps_accounts.installer'

  #####################
  # PS Billing

  ps_billings.context_wrapper:
    class: 'PrestaShopCorp\Billing\Wrappers\BillingContextWrapper'
    arguments:
      - '@ps_accounts.facade'
      - '@rbm_example.context'
      - true # if true you are in sandbox mode, if false or empty not in sandbox

  ps_billings.facade:
    class: 'PrestaShopCorp\Billing\Presenter\BillingPresenter'
    arguments:
      - '@ps_billings.context_wrapper'
      - '@rbm_example.module'

  ps_billings.service:
    class: PrestaShopCorp\Billing\Services\BillingService
    public: true
    arguments:
      - '@ps_billings.context_wrapper'
      - '@rbm_example.module'
