name: Build module RBM
on:
  push:
    branches:
      - main
      - OFF-318/feature/rbm_ci # remove when merging onto main
    paths:
      - 'modules/**'
      - '.github/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Install composer dependencies
        working-directory: ./modules/rbm_example
        run: composer install --no-dev
      - name: Install js dependencies
        working-directory: ./modules/rbm_example/_dev/apps
        run: yarn install --frozen-lockfile
      - name: Clean-up project
        working-directory: ./modules/rbm_example
        run: |
          rm -f composer.*
          rm -f .gitignore
          rm -rf _dev
          ls
        # uses: PrestaShopCorp/github-action-clean-before-deploy@v1.0

