name: Build module RBM
on:
  push:
    branches:
      - main
      - OFF-318/feature/rbm_ci
    paths:
      - 'modules/**'
      # - '.github/**'
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"
