name: Build module RBM
on:
  push:
    branches:
      - main
      - OFF-318/feature/rbm_ci # remove when merging onto main
    paths:
      - 'modules/**'
      - '.github/**'
  # release:
  #   types: [released, prereleased]
env:
  module_path: ./modules/rbm_example
jobs:
  install_build_integration:
    name: Install and build integration dependencies
    runs-on: ubuntu-latest
    env:
      env_name: integration
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - uses: ./.github/actions/install-build-dependencies
        with:
          module_path: ${{env.module_path}}
          env_name: ${{env.env_name}}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: rbm_example_dependencies_${{env.env_name}}
          path: ${{env.module_path}}
  install_build_prestabulle1:
    name: Install and build prestabulle1 dependencies
    runs-on: ubuntu-latest
    env:
      env_name: prestabulle1
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - uses: ./.github/actions/install-build-dependencies
        with:
          module_path: ${{env.module_path}}
          env_name: ${{env.env_name}}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: rbm_example_dependencies_${{env.env_name}}
          path: ${{env.module_path}}
  publish_release:
    name: Publish and release
    runs-on: ubuntu-latest
    needs: install_build_integration
    env:
      env_name: integration
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: rbm_example_dependencies_${{env.env_name}}
      - name: Zip
        run: |
          zip -r rbm_example.zip . -x '*.git*' '*config/config.yml.*'
      - name: Release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./rbm_example.zip
          asset_name: rbm_example_module_${{env.env_name}}.zip
          asset_content_type: application/zip
