name: Build module RBM
on:
  push:
    branches:
      - main
      - OFF-318/feature/rbm_ci # remove when merging onto main
    paths:
      - 'modules/**'
      - '.github/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      module_path: ./modules/rbm_example
      module_path_apps: ${{env.module_path}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Install composer dependencies
        working-directory:  ${{env.module_path}}
        run: composer install --no-dev
      - name: Install js dependencies
        working-directory:  ${{env.module_path_apps}}
        run: yarn install --frozen-lockfile
      - name: Clean-up project
        working-directory:  ${{env.module_path}}
        run: |
          rm -f composer.*
          rm -f .gitignore
          rm -rf _dev
          ls
        # uses: PrestaShopCorp/github-action-clean-before-deploy@v1.0

