name: Build module RBM
on:
  push:
    branches:
      - main
      - OFF-318/feature/rbm_ci # remove when merging onto main
    paths:
      - 'modules/**'
      - '.github/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      module_path: ./modules/rbm_example
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Install composer dependencies
        working-directory: ${{env.module_path}}
        run: composer install --no-dev
      - name: Install js dependencies
        working-directory: ${{env.module_path}}/_dev/apps
        run: yarn install --frozen-lockfile
      - name: Clean-up project
        working-directory: ${{env.module_path}}
        run: |
          rm -f composer.*
          rm -f .gitignore
          rm -f config.xml
          rm -rf _dev
      - uses: actions/upload-artifact@v2
        with:
          name: rbm_example_module
          path: ./modules/rbm_example
  zip:
    name: Zip
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: rbm_example_module