name: Build module RBM
on:
  push:
    branches:
      - main
      - OFF-318/feature/rbm_ci # remove when merging onto main
    paths:
      - 'modules/**'
      - '.github/**'
env:
  module_path: ./modules/rbm_example
jobs:
  install_dependencies:
    name: Install php and js dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Install php dependencies
        working-directory: ${{env.module_path}}
        run: composer install --no-dev
      - name: Install js dependencies
        working-directory: ${{env.module_path}}/_dev/apps
        run: yarn install --frozen-lockfile
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: rbm_example_dependencies
          path: ./modules/rbm_example
  build_integration:
    name: Build integration
    needs: install_dependencies
    runs-on: ubuntu-latest
    env:
      env_name: integration
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: rbm_example_dependencies
      - name: Build ${{env.env_name}} module
        working-directory: ${{env.module_path}}/_dev/apps
        run: yarn add @prestashopcorp/billing-cdc@${{env.env_name}} && yarn build-skip-eslint
      - name: Clean-up project
        working-directory: ${{env.module_path}}
        run: |
          rm -f composer.*
          rm -f .gitignore
          rm -f config.xml
          rm -rf _dev
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: rbm_example_module_${{env.env_name}}
          path: ${{env.module_path}}
  build_prestabulle1:
    name: Build prestabulle1
    needs: install_dependencies
    runs-on: ubuntu-latest
    env:
      env_name: prestabulle1
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: rbm_example_dependencies
      - name: Build ${{env.env_name}} module
        working-directory: ${{env.module_path}}/_dev/apps
        run: yarn add @prestashopcorp/billing-cdc@${{env.env_name}} && yarn build-skip-eslint
      - name: Clean-up project
        working-directory: ${{env.module_path}}
        run: |
          rm -f composer.*
          rm -f .gitignore
          rm -f config.xml
          rm -rf _dev
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: rbm_example_module_${{env.env_name}}
          path: ${{env.module_path}}
  # zip:
  #   name: Zip
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: rbm_example_module